<<<<<<< HEAD
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
=======
# hardware-configuration.nix
>>>>>>> 8538cfd25904310cafc2d19c18be1c440c389b87
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
<<<<<<< HEAD
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
=======
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
>>>>>>> 8538cfd25904310cafc2d19c18be1c440c389b87
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
<<<<<<< HEAD
    { device = "/dev/disk/by-uuid/3ac16171-05bb-41d0-bdf5-2592bafd73d5";
=======
    { device = "/dev/disk/by-uuid/fb9bd0d2-a94f-4199-bad3-5dcd64b6bd33";
>>>>>>> 8538cfd25904310cafc2d19c18be1c440c389b87
      fsType = "ext4";
    };

  fileSystems."/boot" =
<<<<<<< HEAD
    { device = "/dev/disk/by-uuid/9E95-35F6";
=======
    { device = "/dev/disk/by-uuid/D61E-5599";
>>>>>>> 8538cfd25904310cafc2d19c18be1c440c389b87
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
<<<<<<< HEAD
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
=======
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
>>>>>>> 8538cfd25904310cafc2d19c18be1c440c389b87
}
